---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: node-check
  name: node-check
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: node-check
  name: node-check
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-check
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: node-check
  name: node-check
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-check
subjects:
- kind: ServiceAccount
  name: node-check
  namespace: node-check
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-check
  labels:
    app: node-check
spec:
  selector:
    matchLabels:
      app: node-check
  template:
    metadata:
      labels:
        app: node-check
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: NotIn
                values:
                - windows    
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: health-check
        image: supporttools/node-check
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
          - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8888
      hostNetwork: true
      serviceAccountName: node-check
      automountServiceAccountToken: true